name: nodejs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 
          '8.9.0',
          '14.17.5',
          '12.22.5'
        ]

    name: Node JS ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: textbook/git-checkout-submodule-action@master
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      
      - name: Install
        run: npm install
      
      - name: Test
        run: npm test -- --verbose